# Image settings
image_width: 256
image_height: 256

# Camera settings
fov: 38.6
camera_position: [0.278, 0.2744, -0.8]
camera_direction: [0.0, 0.0, 1.0]
world_up: [0.0, 1.0, 0.0]
focus_distance: 0.8

# Rendering settings
samples_per_pixel: 128
num_threads: 8
scene: box
output: output/cornell.png
