image_width: 1920
image_height: 1080
samples_per_pixel: 512
scene: caustics
output: caustics

fov: 50.0
camera_position: [0.0, 3.5, -7.0]
camera_direction: [0.0, -0.25, 1.0]
focus_distance: 7.5

color_window_radius: 1
color_normal_threshold: 0.95
color_depth_threshold: 0.01
var_normal_threshold: 0.95
var_depth_threshold: 0.01
var_compat_sigma: 1.5
