# Image settings
image_width: 320
image_height: 240

# Camera settings
fov: 45.0
camera_position: [0.278, 0.275, -0.9]
camera_direction: [0.0, -0.05, 1.0]
focus_distance: 1.18

# Rendering settings
samples_per_pixel: 128
scene: cornell_box
output: output/cornell.png
