raw: output/cornell_uniform/cornell_uniform.hdr
normal: output/cornell_uniform/cornell_uniform.hdr
albedo: output/cornell_uniform/cornell_uniform.hdr

output: output/denoise

iterations: 5

sigma:
  c: 0.3
  n: 0.2
  a: 0.1
