raw: output/bunny_dof_uniform8/bunny_dof_uniform8_raw.hdr
normal: output/bunny_dof_uniform8/bunny_dof_uniform8_normal.hdr
albedo: output/bunny_dof_uniform8/bunny_dof_uniform8_albedo.hdr

output: output/denoise

iterations: 5

sigma:
  c: 0.5
  n: 0.5
  a: 0.1
