raw: output/cornell_uniform/cornell_uniform.hdr
normal: output/cornell_uniform/cornell_uniform.hdr
albedo: output/cornell_uniform/cornell_uniform.hdr

output: output/denoise

sigma:
  c: 0.3   # color
  n: 0.2   # normal (radians)
  p: 2.0   # pixel/position
  a: 0.1   # albedo
